sonar.organization=lewandowski-anthony
sonar.projectKey=lewandowski-anthony_JiRadar
sonar.projectName=JiRadar
sonar.host.url=https://sonarcloud.io

sonar.modules=back,front

back.sonar.projectBaseDir=back-end
back.sonar.projectName=JiRadar Backend
back.sonar.sources=src/main/java
back.sonar.tests=src/test/java
back.sonar.java.binaries=target/classes
back.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

front.sonar.projectBaseDir=front-end
front.sonar.projectName=JiRadar Frontend
front.sonar.sources=src
front.sonar.tests=src
front.sonar.javascript.lcov.reportPaths=coverage/lcov.info