sonar.organization=jiradar
sonar.projectKey=lewandowski-anthony_JiRadar
sonar.projectName=JiRadar
sonar.host.url=https://sonarcloud.io

sonar.modules=back,front

back.sonar.projectBaseDir=back-end
back.sonar.projectName=JiRadar Backend
back.sonar.sources=src/main/java
back.sonar.tests=src/test/java
back.sonar.java.binaries=back-end/target/classes
back.sonar.coverage.jacoco.xmlReportPaths=back-end/target/site/jacoco/jacoco.xml

front.sonar.projectBaseDir=front-end
front.sonar.projectName=JiRadar Frontend
front.sonar.sources=src
front.sonar.tests=src
front.sonar.exclusions=src/**/*.spec.ts, src/**/*.spec.tsx, **/node_modules/**, **/build-wrapper-dump.json, src/**/constants/**
front.sonar.test.inclusions=src/**/*.spec.ts, src/**/*.spec.tsx
front.sonar.javascript.lcov.reportPaths=front-end/coverage/lcov.info