name: 'Docker Build and Push'
description: 'Helper action to lowercase repository names, set up buildx, and build/push Docker images'

inputs:
  context:
    description: 'Build context path (e.g., ./back-end)'
    required: true
  image_name:
    description: 'The name of the image (e.g., jiradar-back)'
    required: true
  image_tag:
    description: 'The version tag (e.g., 1.0.0)'
    required: true
  push_image:
    description: 'Should the image be pushed ("true" or "false")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lowercase Repository Name
      id: repo
      shell: bash
      run: |
        echo "name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      shell: bash
      run: |
        echo "::group:: [BUILDING] Docker Image Build (${{ inputs.image_name }}:${{ inputs.image_tag }})"
        
        docker buildx build \
          --context ${{ inputs.context }} \
          --file ${{ inputs.context }}/Dockerfile \
          --platform linux/amd64,linux/arm64 \
          --push=${{ inputs.push_image }} \
          --tag ghcr.io/${{ steps.repo.outputs.name }}/${{ inputs.image_name }}:${{ inputs.image_tag }} \
          --tag ghcr.io/${{ steps.repo.outputs.name }}/${{ inputs.image_name }}:latest \
          --cache-from type=gha \
          --cache-to type=gha,mode=max .
        
        echo "::endgroup::"