name: 'Build Maven Back-end'
description: 'Installe Java et build le projet Maven'

inputs:
  java_version:
    description: 'Version of Java to use'
    required: false
    default: '25'
  push_image:
    description: 'Should we push docker image to repository'
    required: true
    default: 'false'
  image_tag:
    description: 'The tag of the Docker image (e.g., 1.0.0)'
    required: true
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Build, Test and Analyze
      shell: bash
      run: |
        cd back-end
        mvn -B clean verify sonar:sonar \
          -Dsonar.organization=jiradar \
          -Dsonar.projectKey=jiradar_jiradar-back \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=src/main/java \
          -Dsonar.tests=src/test/java \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

    - name: Docker Build & Push
      uses: ./.github/actions/docker-build-push
      with:
        context: ./back-end
        image_name: jiradar-back
        image_tag: ${{ inputs.image_tag }}
        push_image: ${{ inputs.push_image }}

    - name: Security Scan Back-end (Trivy)
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/actions/security-scan
      with:
        module-name: "Jiradar Back-end"