spring:
  messages:
    basename:
      - i18n/openapi/openapi
  application:
    name: Jiradar Back
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

jiradar:
  cache:
    enabled: ${CACHE_ENABLED:true}
    provider: ${CACHE_PROVIDER:caffeine}
    specs:
      JIRA_METRICS_CACHE:
        ttl: ${JIRA_METRICS_CACHE_TTL:15m}
        maxSize: ${JIRA_METRICS_CACHE_MAX_SIZE:1000}
      JIRA_USER_CACHE:
        ttl: ${JIRA_USER_CACHE_TTL:2h}
        maxSize: ${JIRA_USER_CACHE_MAX_SIZE:200}

  ai:
    provider: ${JIRADAR_AI_PROVIDER:none}
    ollama:
      base-url: ${OLLAMA_BASE_URL:}
      model-name: ${OLLAMA_MODEL_NAME:ollama-1.0}
    gemini:
      api-key: ${GEMINI_API_KEY:}
      model-name: ${GEMINI_MODEL_NAME:gemini-1.5-pro}
    vertex:
      project-id: ${GCP_PROJECT_ID:}
      location: ${GCP_LOCATION:europe-west1}
      model-name: ${GCP_MODEL_NAME:gemini-1.5-pro}

  issue-tracker:
    metrics:

    jira:
      config:
        enabled: ${JIRA_ENABLED:true}
        url: ${JIRA_URL:http://localhost:8080}
        statuses:
          start-development: ${JIRA_STATUS_START_DEV:In Progress,En cours}
          request-review: ${JIRA_STATUS_REQUEST_REVIEW:In Review,Peer Review}
          done: ${JIRA_STATUS_DONE:Done,Terminé,Validé}


springdoc:
  show-actuator: false
  cache:
    disabled: true

server:
  forward-headers-strategy: framework