spring:
  messages:
    basename:
      - i18n/openapi/openapi
  application:
    name: Jiradar Back
  jackson:
    property-naming-strategy: SNAKE_CASE

issue-tracker:
  jira:
    config:
      enabled: ${JIRA_ENABLED:true}
      url: ${JIRA_URL:http://localhost:8080}
      statuses:
        start-development: ${JIRA_STATUS_START_DEV:In Progress,En cours}
        request-review: ${JIRA_STATUS_REQUEST_REVIEW:In Review,Peer Review}
        done: ${JIRA_STATUS_DONE:Done,Terminé,Validé}

springdoc:
  show-actuator: false
  cache:
    disabled: true