name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '25'
  NODE_VERSION: '20'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created || 'false' }}
      tag_name: ${{ steps.release.outputs.tag_name || 'latest' }}
      prs_created: ${{ steps.release.outputs.prs_created || 'false' }}
      pr: ${{ steps.release.outputs.pr }}
      clean_tag: ${{ steps.format-tag.outputs.version }}
    steps:
      - uses: actions/checkout@v7
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ github.token }}
          release-type: simple

      - name: Format Docker Tag
        id: format-tag
        shell: bash
        run: |
          RAW_TAG="${{ steps.release.outputs.tag_name || 'latest' }}"
          echo "version=${RAW_TAG#v}" >> $GITHUB_OUTPUT

  update-versions:
    runs-on: ubuntu-latest
    needs: release-please
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - name: Link Release PR to an Issue
        uses: ./.github/actions/link-release-issue
        with:
          pr_json: ${{ needs.release-please.outputs.pr }}
          github_token: ${{ github.token }}

      - name: Update Project Versions
        uses: ./.github/actions/update-project-versions
        with:
          pr_output: ${{ needs.release-please.outputs.pr }}

  build-back:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Login to GHCR
        if: needs.release-please.outputs.release_created == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Push Back-end
        uses: ./.github/actions/build-maven
        with:
          push_image: ${{ needs.release-please.outputs.release_created }}
          image_tag: ${{ needs.release-please.outputs.clean_tag }}

  build-front:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Login to GHCR
        if: needs.release-please.outputs.release_created == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Push Front-end
        uses: ./.github/actions/build-node
        with:
          push_image: ${{ needs.release-please.outputs.release_created }}
          image_tag: ${{ needs.release-please.outputs.clean_tag }}
          node_version: ${{ env.NODE_VERSION }}