name: Test Push Image GHCR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to build (e.g., 1.0.0, latest, test)'
        required: true
        default: 'test'
      target_project:
        description: 'Project to test'
        required: true
        type: choice
        options:
          - backend
          - frontend
          - both
        default: 'both'

jobs:
  test-build-back:
    if: ${{ github.event.inputs.target_project == 'backend' || github.event.inputs.target_project == 'both' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Push Back-end (Test)
        uses: ./.github/actions/build-maven
        with:
          push_image: 'true'
          image_tag: ${{ github.event.inputs.image_tag }}

  test-build-front:
    if: ${{ github.event.inputs.target_project == 'frontend' || github.event.inputs.target_project == 'both' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Push Front-end (Test)
        uses: ./.github/actions/build-node
        with:
          push_image: 'true'
          image_tag: ${{ github.event.inputs.image_tag }}